// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2xj40d13SXY82wOE9Gu9crSAtrrWnYLQ',
    appId: '1:677407184955:android:349b418970f686a87e241e',
    messagingSenderId: '677407184955',
    projectId: 'nyanime-tech',
    storageBucket: 'nyanime-tech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8bxchRY4nQmBvehaBVvJ9vMTa-MjABVk',
    appId: '1:677407184955:ios:000afba67536fadd7e241e',
    messagingSenderId: '677407184955',
    projectId: 'nyanime-tech',
    storageBucket: 'nyanime-tech.firebasestorage.app',
    iosClientId: '677407184955-7oemjg7rvkr315bpvoll5qhqqmv2lplu.apps.googleusercontent.com',
    iosBundleId: 'com.example.nylab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8bxchRY4nQmBvehaBVvJ9vMTa-MjABVk',
    appId: '1:677407184955:ios:000afba67536fadd7e241e',
    messagingSenderId: '677407184955',
    projectId: 'nyanime-tech',
    storageBucket: 'nyanime-tech.firebasestorage.app',
    iosClientId: '677407184955-7oemjg7rvkr315bpvoll5qhqqmv2lplu.apps.googleusercontent.com',
    iosBundleId: 'com.example.nylab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfwO_c-_BbkiI0NcipTvGIya_R1EYyyTI',
    appId: '1:677407184955:web:920f54a27a41c1337e241e',
    messagingSenderId: '677407184955',
    projectId: 'nyanime-tech',
    authDomain: 'nyanime-tech.firebaseapp.com',
    storageBucket: 'nyanime-tech.firebasestorage.app',
    measurementId: 'G-L1MKR2K0VF',
  );
}
